### ISSUE TITLE
Upgrade to puid ~> 2.2

### ISSUE THREAD

**Issue by Rodeoclash** [Digital-Identity-Labs/prefixed_api_key#1]
Great library, thanks for making it. I notice that it doesn't support puid > 2 yet. Would you be interested in a PR that (attempts) to upgrade to puid 2?

**Comment by binaryape** [comment]
Yes I would, thanks! I've been distracted and keep forgetting to update it, I appreciate the nudge and if you can provide a PR too I'll get that merged and published ASAP. Glad you find it useful!

**Comment by binaryape** [comment]
Hi, I've released a patch update (0.2.1) that should resolve this issue - sorry about the delay
